name: Victor Jiao
hobbies:
    - "going to hackathons, "
    - "making cool things, "
voices: "http://voicesinyourhead.org/"
school: the University of Chicago
major: Computer Science
degree: BS
graduatingYear: 2018

